version: "3.7"

services:

  # 1c-server:
    # environment:
    #   - PLATFORM_VERSION=${PLATFORM_VERSION}
    private:
      image: 10.3.80.70:5000/1c-server:8.3.20.1996
    # build:
    #   context: ./1c-server
    ports:
      - '1540-1541:1540-1541'
      - '1560-1591:1560-1591'
    # depends_on:
    #   - test-postgres
    restart: always
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    volumes:
      - ./1c-server-home:/home/usr1cv8
      - ./1c-server-logs:/var/log/1C
      - /etc/localtime:/etc/localtime:ro

    # postgres:
    #   image: silverbulleters/ya-docker-postgresql-1c:latest
    #   tmpfs:
    #     - /var/lib/pgpro/1c-11/temptblspc
    #   networks:
    #     - pgdb_network
    #   environment:
    #     - USETMPFS_FOR_TMP=true
    #     - DEBUG=false
    #     - DB_NAME=powa,mamonsu
    #     - POWA_DATABASE=powa
    #     - PG_TUNE_BY_MAMONSU=true
    #     - PG_MAX_CONNECTION=130
    #     - PG_TIMEZONE=Europe/Moscow
    #   env_file:
    #     ./.env
    #   ports:
    #     - target: 5432
    #       published: 5432
    #       protocol: tcp
    #       mode: host
    #   deploy:
    #     mode: replicated
    #     replicas: 1
    #     placement:
    #       constraints: [node.labels.dbrole == "master" ]
    #   volumes:
    #     - pg-data-master:/var/lib/pgpro/1c-10/main
    #     - pg-v81cdata-master:/var/lib/pgpro/1c-10/v81c_data
    #     - pg-v81cindex-master:/var/lib/pgpro/1c-10/v81c_index
    #     - pg-log-master:/var/log/postgresql
