version: '3'
services:
    postgres:
        # image: postgres:latest
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    1c-server:
      image: 1c-server:8.3.19-1522
      environment:
        - PLATFORM_VERSION=${PLATFORM_VERSION}
        - SERVER_VERSION=${SERVER_VERSION}
      build:
        context: ./1c-server
      ports:
        - '1540-1541:1540-1541'
        - '1560-1591:1560-1591'
      # depends_on:
      #   - test-postgres
      restart: always
      deploy:
        restart_policy:
          condition: any
          delay: 5s
          window: 120s
      volumes:
        - ./1c-server-home:/home/usr1cv8
        - ./1c-server-logs:/var/log/1C
        - /etc/localtime:/etc/localtime:ro