version: '3'

services:
  1c-server:
    image: 10.3.80.70:5000/1c-server:$PLATFORM_VERSION
    container_name: 1c-server
    ports:
      - '1540-1541'
      - '1560-1591'
    environment:
      - PLATFORM_VERSION=${PLATFORM_VERSION}
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./1c-server-home:/home/usr1cv8
      - ./1c-server-logs:/var/log/1C
      - /etc/localtime:/etc/localtime:ro

  postgres:
    image: 10.3.80.70:5000/postgrespro-1c:$PG_VERSION
    container_name: postgrespro-1c
    env_file:
      ./.env
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   placement:
    #     constraints: [node.labels.dbrole == "master" ]
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
